input:
  path: experiments/prep_videos/test0_prep.mp4 #experiments/images/pandeja.png #

output:
  json: experiments/outputs/test0_prep_detections.json
  
models:
  pose: yolo11n-pose.pt
  ball: yolo11n.pt
  confidence: 0.4
  proximity: 0.2
