input:
  path: experiments/images/pandeja.png #experiments/raw_videos/test.mp4

output:
  json: experiments/outputs/detections.json
  annot_dir: experiments/outputs

preprocess:
  num_frames: 0     # skip by default
  start_sec: 0.0
  end_sec: null
  
models:
  pose: yolo11n-pose.pt
  ball: yolo11n.pt
  confidence: 0.4
  proximity: 0.2
