input:
  path: experiments/images/pandeja.png #experiments/prep_videos/test0_prep.mp4 

output:
  json: experiments/outputs/pandeja_detections.json
  
models:
  pose: yolo11n-pose.pt
  ball: yolo11n.pt
  confidence: 0.4
  proximity: 0.2
